<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

/**
 * this is only for read - CQRS
 * Class ReadMotorBikeModel
 * @package App
 */
class ReadMotorBikeModel extends Model
{
    protected $table = 'motor_bike';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [];

    /**
     *
     * ReadMotorBikeModel constructor.
     * prevent write
     *
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct([]);
    }

    public function create(array $attributes = [])
    {
        throw new \Exception("this class is only for reporting purpose ");
    }

    public function save(array $options = [])
    {
        throw new \Exception("this class is only for reporting porpose ");
        //return parent::save([]); // TODO: Change the autogenerated stub
    }

}
